### ISSUE TITLE
Project Checkpoint Feedback

### ISSUE THREAD

**Issue by poojapathak1725** [COGS118A/Group045-Wi23#4]
Project Checkpoint Grade - 9/9

Title and Abstract(0.75/0.75) - 
Display title of project in bold. 
Ok - just fix minor typos. 

Background (1/1) - Good. Mention that the two models are your benchmark models and whether you expect to see similar results. 
(Then at the end of the project, discuss your results, and whether you reached this result - why or why not etc.)

Problem Statement (1/1) - Good, just mention the classifiers you plan to use. 

Data (1.25/1.25) - 
Good. 

Proposed Solution (1.25/1.25)- 
Good. 

Metrics (1.25/1.25) - 
Express your metrics in the context of your problem as well (What are false positives in this case? False Negatives? Which mistake is more costly?) Make sure the equations are in proper math notation. 

Preliminary Results (1.5/1.5) - 
Conduct some preliminary EDA before going right into Model Prep. For eg. histograms/bar plots showing distributions of your critical features + Correlation heatmap to explore the correlation between your features/explore which feature is most predictive of heart disease. Otherwise great start!

Ethics and Privacy (0.5/0.5)  - 
Good job identifying the potential risks of working with heart disease datasets but how are YOU ensuring your work addresses these ethical issues? Explain from the context of your work.

Team Expectations (0.25/0.25) - 

Timeline (0.25/0.25) - 

Other Comments - Great start so far, just keep this feedback in mind for the Final Project. 

You can reply to this feedback below. Contact me anytime if you want help improving your project or have any questions at all!

**Comment by poojapathak1725** [comment]
Copying questions from email here - 
I have a few questions regarding the checkpoint comments and also the final project expectation.

I am not sure as to what you meant by 
1) "Problem Statement (1/1) - Good, just mention the classifiers you plan to use." Should I just delete everything in this problem statement section, and just mentioning what classifiers I plan to use is enough? Because I mentioned the classifiers in the proposed solution, should I just copy and paste that part to the problem statement and keep both?

 Answer : _Keep everything you currently have in problem statement, add a line (so copy and paste from proposed solution) what classifiers you plan to use to solve this problem_

2) For evaluation metrics, "Make sure the equations are in proper math notation". Do you mean, in my case, for example I should use division as in mathematical notation, not "/"?

Answer : _Display the metrics as fractions with proper formatting_

3) Looking at the template for the final project, am I correct in thinking that the grade will be based partly on our effort in incorporating the checkpoint comments to the final project and partly on completion?

Answer: _Yes, and completing all required steps as detailed for you in the Final Project Template_

Hope this helps, you can post a reply here if anything is unclear.

**Comment by ricky-trn** [comment]
Thank you for the clarification, Pooja. This is very helpful!

**Comment by ricky-trn** [comment]
I just uploaded the final project and want let you know the anchor tags do not seem to work on repo, although they should work on jupyter notebook @poojapathak1725. Thank you.

**Comment by poojapathak1725** [comment]
That's fine - thanks for letting me know.

**Comment by ricky-trn** [comment]
Final template does not contain team expectation and schedule parts like checkpoint and proposal and I see other groups have those parts in their final project submission. Do I need to insert those parts to my final project submission as well? @poojapathak1725. Thank you.

**Comment by poojapathak1725** [comment]
There are no points assigned for team expectations and schedule for the final project - so it's ok if you don't include them.
